練習課題7「入学のご案内」
ryoma-yama/markup_kadai_07 pull request #1
Opened 2020-03-10 17:02 UTC by ryoma-yama

### やったこと
- テーブルタグを使いました。
- PDFを忠実に再現するために`p`要素にデフォルトでついているmarginを0pxとして、改行が必要なところにはmargin-topで擬似的に改行を入れました。なお、この際に値を16pxとしたのはデフォルトのmarginをディベロッパーツールで計測した際に出た値だからです。

2020-04-02 12:20 UTC, ryoma-yama commented
3352525 にて課題内容変更に合わせてCSSファイルの置き換えと追記を行いました。
- 追記内容は`th`のコンテンツの中央寄せと太字化です。

2020-04-06 03:32 UTC, piasoratech requested changes
コメントしたので確認お願いします！

2020-04-06 03:32 UTC, piasoratech commented on markup_kadai_2.html
> +      <p>（当日はノートに書いてある待ち合わせ場所ではなく、ノート一番下に記載ある教室まで直接お越しくださいませ）</p>
ここは`p`タグ内で改行するようにして対応しましょう。

2020-04-06 06:37 UTC, ryoma-yama commented
a9c0ec0 にて、該当箇所を段落内での改行に変更しました。

2020-04-07 02:27 UTC, piasoratech approved these changes
ＯＫです！

2020-04-18 00:25 UTC, merged